### ISSUE TITLE
Close nodes when finding a solution

### ISSUE THREAD

**Issue by dhendryc** [Wikunia/Bonobo.jl#16]
Hello,
I just tested a binary minimization problem using the Bonobo tree structure and realized that even after finding a possible optimal solution nodes were evaluated whose parent had a worse lower bound than the incumbent. I checked the source code and I think the issue stems from the fact then a new node is added its lower bound is always set to -Inf. (nodes.jl line 51)

function add_node!(tree::BnBTree{Node}, node_info::NamedTuple) where Node <: AbstractNode
    node_id = tree.num_nodes + 1
    node = create_node(Node, node_id, node_info)
    tree.nodes[node_id] = node
    tree.num_nodes += 1
end

function create_node(Node, node_id::Int, node_info::NamedTuple)
    bnb_node = structfromnt(BnBNodeInfo, (id = node_id, lb = -Inf, ub = Inf))   # here!
    bnb_nt = (std = bnb_node,)
    node_nt = merge(bnb_nt, node_info)
    return structfromnt(Node, node_nt)
end

The node should inherit the lower bound from its parent otherwise we can never close nodes without evaluating them.

**Comment by Wikunia** [comment]
Thanks for opening the issue. I might have some time to fix it in about 7 hours but feel free to open a PR yourself. Your suggestion sounds valid.
