### ISSUE TITLE
When should tree.lb be updated

### ISSUE THREAD

**Issue by matbesancon** [Wikunia/Bonobo.jl#21]
We realized recently that tree.lb is never used nor updated(in Bonobo nor in the user implementation)

When should it be done? Should it be included in the Bonobo mechanism in itself or expected in one of the user functions?

The moment at which it should be done is also non-trivial to determine, after having processed all the children of the node that was previously the current active lower bound?

**Comment by Wikunia** [comment]
Hmm I see, we should definitely use it to early stop when an incumbent achieves the bound, right?
It should always be the minimum lower bound of all leaf nodes, right? I would assume one could use a standard priority queue which deletes a node when it's branched on and both children are evaluated. Also adds the new processed ones to it. Not sure how time consuming this is.

**Comment by matbesancon** [comment]
> Hmm I see, we should definitely use it to early stop when an incumbent achieves the bound, right?

Yes absolutely

> It should always be the minimum lower bound of all leaf nodes, right?

Yes but the trick is when is the minimum evaluated. It's fine if each child node inherits the lb from its parent (it's a valid lb after all) even before being processed
