### ISSUE TITLE
branching and traversing strategies should take in values, not types

### ISSUE THREAD

**Issue by matbesancon** [Wikunia/Bonobo.jl#32]
``` 
    traverse_strategy = BFS,
    branch_strategy = FIRST,
```
should be 
``` 
    traverse_strategy = BFS(),
    branch_strategy = FIRST(),
```
and overall expect values with subtypes of AbstractXY.

The reason is that some additional strategies might take parameters stored as values

**Comment by Wikunia** [comment]
I had the same thought last night 😂 yes it should!

**Comment by matbesancon** [comment]
my use case here for instance is strong branching, which should definitely be tuned
