### ISSUE TITLE
Support for heuristic callback?

### ISSUE THREAD

**Issue by mohamed82008** [Wikunia/Bonobo.jl#45]
Hi, thanks for this really cool package! Does Bonobo support heuristic callbacks?

**Comment by matbesancon** [comment]
Hi, very good point we haven't added a mechanic for it yet but this should be doable directly.

Technically one can pass solutions to Bonobo directly but we'll make something nicer for the root node.
For a proper callback we will document it but this should be doable fairly smoothly, since we are already adding MIP heuristics in the Bonobo callback

**Comment by mohamed82008** [comment]
>One can push solutions to the Solution storage in the callback passed to the main optimizing function I think

Thanks @matbesancon. That's neat. The first argument `tree` has a field `solutions`. Pushing a solution there is what you mean?

**Comment by matbesancon** [comment]
yes exactly, except you should also update `tree.incumbent` if the solution is a better than the current one

**Comment by mohamed82008** [comment]
I see, thanks.

**Comment by matbesancon** [comment]
It would be worth adding it to the docs if you have time

**Comment by mohamed82008** [comment]
I was exploring the possibility of doing this for a potential internship project in Pumas. Now that I know it's doable, if the intern starts working on this project, I will ask him to contribute to the docs here. The project will likely also involve Boscia, comparing it to Juniper for constrained model-based optimal design of experiments. I will keep you posted if you are interested in collaborating on this.

**Comment by mohamed82008** [comment]
>I will keep you posted if you are interested in collaborating on this.

By co-mentoring or answering questions for example. A paper draft will likely come out of this work.

**Comment by matbesancon** [comment]
great, I'd definitely be interested in following up, we are also comparing Boscia to some other solvers and methods on various use cases now
